### PR TITLE
Update to TDP MEP Page 

### PR DESCRIPTION
**Pull request by catholichighsec**
Updated Selection Exercise info for 2024 and the corresponding dates provided according to the email from Claire

### CODE REVIEW

**Comment by catholichighsec** [comment]
Included School Canteen Primary which Verified with Chen yuan already that it is ready to go

**Review by yianhoon — APPROVED** [review]

**Review by yianhoon — COMMENTED** [review]
Good to go

**Review by yianhoon — COMMENTED** [review]
Good to go.

**Review by yianhoon — COMMENTED** [review]
Good to go.

**Pull request merged**
